Title: Bamba Magic Kingdom
Alternate Titles: null
Library: arcade
Series: null
Developer: E-Dologic and Playful Shark
Publisher: osem
Play Mode: Single Player
Release Date: null
Version: null
Languages: he
Extreme: No
Tags: RPG
Tag Categories: default
Source: null
Platform: Flash
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://www.magic-kingdom.live/static/game/BambaMain.swf
Game Notes: null
Original Description: null
Curation Notes: null
Additional Applications: {}
